name: dsh
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.4.0

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
